"""Alert management for sensor anomalies and system events."""

from __future__ import annotations

import enum
import logging
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


class AlertLevel(enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


@dataclass
class Alert:
    """An alert generated by the system."""
    level: AlertLevel
    alert_type: str
    message: str
    timestamp: float = field(default_factory=time.time)
    source: str = ""
    sensor_id: str = ""
    details: Dict[str, Any] = field(default_factory=dict)
    alert_id: str = ""

    def __post_init__(self) -> None:
        if not self.alert_id:
            self.alert_id = f"{self.level.value}:{self.alert_type}:{self.timestamp:.2f}"


class AlertManager:
    """Manages alerts: threshold checks, anomaly detection, callback dispatch."""

    def __init__(self, dedup_window: float = 60.0, max_history: int = 1000) -> None:
        self.dedup_window = dedup_window
        self._max_history = max_history
        self._handlers: Dict[AlertLevel, List[Callable[[Alert], None]]] = {
            level: [] for level in AlertLevel
        }
        self._thresholds: Dict[str, Dict[str, Any]] = {}  # sensor_id -> {min, max, warn_min, warn_max}
        self._history: List[Alert] = []
        self._dedup_cache: Dict[str, float] = {}
        self._lock = threading.Lock()

    def register_handler(self, level: AlertLevel, callback: Callable[[Alert], None]) -> None:
        self._handlers[level].append(callback)

    def set_threshold(
        self,
        sensor_id: str,
        warn_min: Optional[float] = None,
        warn_max: Optional[float] = None,
        crit_min: Optional[float] = None,
        crit_max: Optional[float] = None,
    ) -> None:
        self._thresholds[sensor_id] = {
            "warn_min": warn_min, "warn_max": warn_max,
            "crit_min": crit_min, "crit_max": crit_max,
        }

    def check_threshold(self, sensor_id: str, value: float, source: str = "") -> List[Alert]:
        """Check a value against configured thresholds. Returns triggered alerts."""
        thresholds = self._thresholds.get(sensor_id)
        if not thresholds or value is None:
            return []

        alerts: List[Alert] = []
        if thresholds.get("crit_min") is not None and value < thresholds["crit_min"]:
            alerts.append(Alert(
                level=AlertLevel.CRITICAL, alert_type="threshold",
                message=f"{sensor_id} critically low: {value:.2f} < {thresholds['crit_min']}",
                sensor_id=sensor_id, source=source,
                details={"value": value, "threshold": thresholds["crit_min"]},
            ))
        elif thresholds.get("warn_min") is not None and value < thresholds["warn_min"]:
            alerts.append(Alert(
                level=AlertLevel.WARNING, alert_type="threshold",
                message=f"{sensor_id} below warning: {value:.2f} < {thresholds['warn_min']}",
                sensor_id=sensor_id, source=source,
                details={"value": value, "threshold": thresholds["warn_min"]},
            ))

        if thresholds.get("crit_max") is not None and value > thresholds["crit_max"]:
            alerts.append(Alert(
                level=AlertLevel.CRITICAL, alert_type="threshold",
                message=f"{sensor_id} critically high: {value:.2f} > {thresholds['crit_max']}",
                sensor_id=sensor_id, source=source,
                details={"value": value, "threshold": thresholds["crit_max"]},
            ))
        elif thresholds.get("warn_max") is not None and value > thresholds["warn_max"]:
            alerts.append(Alert(
                level=AlertLevel.WARNING, alert_type="threshold",
                message=f"{sensor_id} above warning: {value:.2f} > {thresholds['warn_max']}",
                sensor_id=sensor_id, source=source,
                details={"value": value, "threshold": thresholds["warn_max"]},
            ))

        for alert in alerts:
            self.emit(alert)
        return alerts

    def emit(self, alert: Alert) -> None:
        """Emit an alert (with deduplication)."""
        with self._lock:
            # Dedup
            dedup_key = f"{alert.alert_type}:{alert.sensor_id}"
            last_time = self._dedup_cache.get(dedup_key, 0)
            if time.time() - last_time < self.dedup_window:
                return
            self._dedup_cache[dedup_key] = time.time()

            self._history.append(alert)
            if len(self._history) > self._max_history:
                self._history = self._history[-self._max_history:]

        for handler in self._handlers.get(alert.level, []):
            try:
                handler(alert)
            except Exception:
                logger.exception("Alert handler error")

    def get_history(
        self,
        level: Optional[AlertLevel] = None,
        since: Optional[float] = None,
        limit: int = 100,
    ) -> List[Alert]:
        with self._lock:
            history = list(self._history)
        if level:
            history = [a for a in history if a.level == level]
        if since:
            history = [a for a in history if a.timestamp >= since]
        return history[-limit:]

    def clear_history(self) -> None:
        with self._lock:
            self._history.clear()
            self._dedup_cache.clear()
