"""Multi-agent AI system: Planner, Predictor, Optimizer with feedback loops."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np

from .predictor import SimplePredictor
from .optimizer import ResourceAllocator

logger = logging.getLogger(__name__)


@dataclass
class Plan:
    """A plan generated by the PlannerAgent."""
    goal: str
    sub_tasks: List[Dict[str, Any]] = field(default_factory=list)
    agent_assignments: Dict[str, str] = field(default_factory=dict)
    priority: float = 0.5
    estimated_ticks: int = 100

    def to_dict(self) -> Dict[str, Any]:
        return {
            "goal": self.goal,
            "sub_tasks": self.sub_tasks,
            "agent_assignments": self.agent_assignments,
            "priority": self.priority,
            "estimated_ticks": self.estimated_ticks,
        }


class PlannerAgent:
    """
    Analyzes scenarios and creates execution plans.
    Decomposes goals into sub-tasks and assigns to specialist agents.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}

    def plan(self, scenario_config: Dict[str, Any], current_state: Dict[str, Any]) -> Plan:
        """Analyze scenario and create a plan."""
        goal = self._derive_goal(scenario_config, current_state)
        sub_tasks = self._decompose(goal, scenario_config)
        assignments = self._assign_agents(sub_tasks, scenario_config)

        return Plan(
            goal=goal,
            sub_tasks=sub_tasks,
            agent_assignments=assignments,
            priority=scenario_config.get("priority", 0.5),
            estimated_ticks=scenario_config.get("duration", 100),
        )

    def _derive_goal(self, config: Dict, state: Dict) -> str:
        name = config.get("name", "general")
        goals = {
            "smart_city_traffic": "Minimize congestion while maintaining energy efficiency",
            "factory_optimization": "Maximize production throughput under energy constraints",
            "energy_balancing": "Balance energy supply and demand across all zones",
            "emergency_failure": "Maintain system stability under failure conditions",
        }
        return goals.get(name, "Optimize overall system efficiency and stability")

    def _decompose(self, goal: str, config: Dict) -> List[Dict[str, Any]]:
        tasks = [
            {"name": "monitor_resources", "type": "observe", "frequency": "every_tick"},
            {"name": "predict_demand", "type": "predict", "frequency": "every_10_ticks"},
            {"name": "allocate_resources", "type": "optimize", "frequency": "every_5_ticks"},
            {"name": "detect_anomalies", "type": "detect", "frequency": "every_tick"},
            {"name": "adjust_parameters", "type": "control", "frequency": "on_drift"},
        ]
        if "energy" in goal.lower():
            tasks.append({"name": "balance_energy_grid", "type": "optimize", "frequency": "every_10_ticks"})
        if "failure" in goal.lower():
            tasks.append({"name": "failure_recovery", "type": "control", "frequency": "on_event"})
        return tasks

    def _assign_agents(self, tasks: List[Dict], config: Dict) -> Dict[str, str]:
        agent_map = {
            "observe": "predictor",
            "predict": "predictor",
            "optimize": "optimizer",
            "detect": "predictor",
            "control": "optimizer",
        }
        return {t["name"]: agent_map.get(t["type"], "optimizer") for t in tasks}


class PredictorAgent:
    """
    Runs predictions on current state.
    Wraps SimplePredictor with domain-specific logic.
    """

    def __init__(self, window_size: int = 20):
        self.predictors: Dict[str, SimplePredictor] = {}
        self._window = window_size

    def predict(self, state: Dict[str, Any], horizon: int = 5) -> Dict[str, Any]:
        """Generate predictions for key metrics."""
        predictions = {}
        for key in ["total_energy_consumption", "total_production", "efficiency",
                     "throughput", "resource_utilization", "stability"]:
            value = state.get(key, 0.0)
            if isinstance(value, (int, float)):
                if key not in self.predictors:
                    self.predictors[key] = SimplePredictor(window_size=self._window)
                self.predictors[key].update(value)
                predictions[f"predicted_{key}"] = self.predictors[key].predict_next()

        predictions["horizon"] = horizon
        predictions["confidence"] = self._estimate_confidence(state)
        return predictions

    def _estimate_confidence(self, state: Dict[str, Any]) -> float:
        """Estimate prediction confidence based on data availability."""
        if not self.predictors:
            return 0.0
        lengths = [len(p._history) for p in self.predictors.values()]
        avg_len = np.mean(lengths) if lengths else 0
        return min(1.0, avg_len / 100.0)


class OptimizerAgent:
    """
    Applies optimizations based on predictions and current state.
    """

    def __init__(self, total_budget: float = 2000.0):
        self._allocator = ResourceAllocator(total_budget=total_budget, method="lp")

    def optimize(self, state: Dict[str, Any], predictions: Dict[str, Any],
                 agent_states: Dict[str, Any]) -> Dict[str, Any]:
        """Generate optimization actions."""
        # Resource allocation based on predicted demand
        demands = {aid: max(0.01, a.get("energy_consumption", 1.0))
                   for aid, a in agent_states.items()}
        
        # Weight by predicted energy needs
        priorities = {}
        for aid, a in agent_states.items():
            atype = a.get("agent_type", "unknown")
            priorities[aid] = {"energy": 2.0, "machine": 1.5, "vehicle": 1.0,
                               "human": 0.8}.get(atype, 1.0)

        allocations = self._allocator.allocate(demands, priorities)
        
        # Compute optimization metrics
        total_allocated = sum(allocations.values())
        total_demand = sum(demands.values())
        coverage = total_allocated / total_demand if total_demand > 0 else 0

        return {
            "allocations": allocations,
            "coverage": round(coverage, 4),
            "total_allocated": total_allocated,
            "unmet_demand": total_demand - total_allocated,
            "strategy": "lp_priority_based",
            "predicted_efficiency_gain": predictions.get("predicted_efficiency", 0) * 0.1,
        }


class AgentCoordinator:
    """
    Orchestrates the multi-agent AI loop.
    
    Flow: Simulation → Planner → Predictor → Optimizer → Updated Simulation
    With feedback: results feed back into next cycle.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}
        self.planner = PlannerAgent(config)
        self.predictor = PredictorAgent()
        self.optimizer = OptimizerAgent(
            total_budget=config.get("energy_budget", 2000)
        )
        self._plan: Optional[Plan] = None
        self._history: List[Dict[str, Any]] = []
        self._feedback_window: List[Dict[str, Any]] = []
        self._drift_detected = False

    def initialize(self, scenario_config: Dict[str, Any], initial_state: Dict[str, Any]) -> None:
        """Initialize with scenario config and create initial plan."""
        self._plan = self.planner.plan(scenario_config, initial_state)
        logger.info(f"Plan created: {self._plan.goal}")

    def coordinate(self, tick: int, state: Dict[str, Any],
                   env_state: Dict[str, Any], agent_states: Dict[str, Any]) -> Dict[str, Any]:
        """
        Run one coordination cycle: predict → optimize → feedback.
        Returns combined actions for the simulation engine.
        """
        # 1. Predict
        predictions = self.predictor.predict(state, horizon=5)

        # 2. Optimize based on predictions
        optimizations = self.optimizer.optimize(state, predictions, agent_states)

        # 3. Check for drift (feedback)
        drift = self._check_drift(tick, state, predictions)
        if drift["drift_detected"]:
            self._drift_detected = True
            optimizations["drift_correction"] = drift["correction"]
            logger.info(f"Drift detected at tick {tick}: {drift['details']}")

        # 4. Record
        cycle_result = {
            "tick": tick,
            "plan_goal": self._plan.goal if self._plan else "none",
            "predictions": predictions,
            "optimizations": optimizations,
            "drift": drift,
        }
        self._history.append(cycle_result)
        if len(self._history) > 10000:
            self._history = self._history[-10000:]

        return {
            "predictions": predictions,
            "optimizations": optimizations,
            "plan": self._plan.to_dict() if self._plan else None,
        }

    def _check_drift(self, tick: int, state: Dict, predictions: Dict) -> Dict[str, Any]:
        """Check if actual metrics deviate from predictions."""
        self._feedback_window.append({"tick": tick, "state": state, "predictions": predictions})
        if len(self._feedback_window) > 50:
            self._feedback_window = self._feedback_window[-50:]

        if len(self._feedback_window) < 10:
            return {"drift_detected": False, "details": "insufficient_data"}

        # Compare recent actuals vs predictions
        actuals = [w["state"].get("total_energy_consumption", 0) for w in self._feedback_window[-10:]]
        preds = [w["predictions"].get("predicted_total_energy_consumption", 0) for w in self._feedback_window[-10:]]

        if not actuals or not preds:
            return {"drift_detected": False, "details": "no_data"}

        errors = [abs(a - p) for a, p in zip(actuals, preds)]
        mean_error = float(np.mean(errors))
        std_error = float(np.std(errors)) if len(errors) > 1 else 0

        drift_threshold = self.config.get("drift_threshold", 50.0)
        drift_detected = mean_error > drift_threshold

        correction = {}
        if drift_detected:
            correction["adjust_budget"] = mean_error * 1.2
            correction["increase_monitoring"] = True

        return {
            "drift_detected": drift_detected,
            "mean_error": round(mean_error, 2),
            "std_error": round(std_error, 2),
            "details": f"mean_error={mean_error:.1f}, threshold={drift_threshold}",
            "correction": correction,
        }

    def get_history(self) -> List[Dict[str, Any]]:
        return list(self._history)

    def get_summary(self) -> Dict[str, Any]:
        if not self._history:
            return {"status": "no_data"}
        drift_count = sum(1 for h in self._history if h.get("drift", {}).get("drift_detected"))
        return {
            "cycles_completed": len(self._history),
            "drift_events": drift_count,
            "drift_rate": drift_count / len(self._history) if self._history else 0,
            "current_plan": self._plan.to_dict() if self._plan else None,
        }

    def step(self, tick: int, state: Dict[str, Any], env_state: Dict[str, Any],
             agent_states: Dict[str, Any]) -> Dict[str, Any]:
        """AI module interface — compatible with SimulationEngine."""
        return self.coordinate(tick, state, env_state, agent_states)
